### ISSUE TITLE
Broken Cask: octicons (5.0.1) missing `.tff` file

### ISSUE THREAD

**Issue by bsbodden** [caskroom/homebrew-fonts#1300]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Missing Font source `build/font/octicons.ttf`
The whole build directory is missing

#### Output of your command with `--verbose --debug`

```
$ brew cask install font-octicons --verbose --debug

==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/primer/octicons/archive/v5.0.1.zip
Already downloaded: /Users/bsb/Library/Caches/Homebrew/Cask/font-octicons--5.0.1.zip
==> Downloaded to -> /Users/bsb/Library/Caches/Homebrew/Cask/font-octicons--5.0.1.zip
==> Verifying download
==> Determining which verifications to run for Cask font-octicons
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask font-octicons
==> SHA256 checksums match
==> Installing Cask font-octicons
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/bsb/Library/Caches/Homebrew/Cask/font-octicons--5.0.1.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/bsb/Library/Caches/Homebrew/Cask/font-octicons--5.0.1.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/bsb/Library/Caches/Homebrew/Cask/font-octicons--5.0.1.zip", "/var/folders/yz/d1kw6nlx083bjpzl19m459180000gn/T/d20170911-91592-15nvumi"]
==> Creating metadata directory /usr/local/Caskroom/font-octicons/.metadata/5.0.1/20170911231038.168.
==> Creating metadata subdirectory /usr/local/Caskroom/font-octicons/.metadata/5.0.1/20170911231038.168/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask font-octicons
==> 1 artifact/s defined
octicons-5.0.1/build/font/octicons.ttf (Font)
==> Installing artifact of class Hbc::Artifact::Font
==> Purging files for version 5.0.1 of Cask font-octicons
Error: It seems the Font source '/usr/local/Caskroom/font-octicons/5.0.1/octicons-5.0.1/build/font/octicons.ttf' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:37:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2-50-gda742d8
caskroom/homebrew-cask (git revision df78ff; last commit 2017-09-12)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 90.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3727 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1113 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/.rvm/gems/ruby-2.3.3/bin:~/.rvm/gems/ruby-2.3.3@global/bin:~/.rvm/rubies/ruby-2.3.3/bin:/usr/local/opt/imagemagick@6/bin:~/.jenv/shims:~/.jenv/bin:/usr/local/sbin:/usr/local/bin:~/.bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.rvm/bin:/usr/local/Homebrew/Library/Taps/gapple/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-fonts/pull/1301
