### ISSUE TITLE
font-et-book fails to install

### ISSUE THREAD

**Issue by d1rk** [caskroom/homebrew-fonts#1339]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Installing font-et-book via `brew cask install font-et-book` exits with an Error: `Error: Is a directory - read`

I wonder if I need to specify a variation to be installed? It says, there are five Artifacts to be installed, via `brew cask info font-et-book`:

```
==> Artifacts
et-book-bold-line-figures/et-book-bold-line-figures.ttf (Font)
et-book-display-italic-old-style-figures/et-book-display-italic-old-style-figures.ttf (Font)
et-book-roman-line-figures/et-book-roman-line-figures.ttf (Font)
et-book-roman-old-style-figures/et-book-roman-old-style-figures.ttf (Font)
et-book-semi-bold-old-style-figures/et-book-semi-bold-old-style-figures.ttf (Font)

```

Thank you for your help. It is greatly appreciated.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Checking out https://github.com/edwardtufte/et-book/trunk/et-book
==> Executing: ["/usr/bin/svn", "checkout", "--force", "--config-option", "config:miscellany:use-commit-times=yes", "--trust-server-cert", "--non-interactive", "https://github.com/edwardtufte/et-book/trunk/et-book", "/Users/d1rk/Library/Caches/Homebrew/Cask/font-et-book--svn", "-r", "50"]
==> Downloaded to -> /Users/d1rk/Library/Caches/Homebrew/Cask/font-et-book--svn
==> Verifying download
==> Determining which verifications to run for Cask font-et-book
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask font-et-book, skipping verification
==> 0 verifications defined
==> Installing Cask font-et-book
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/d1rk/Library/Caches/Homebrew/Cask/font-et-book--svn"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Checking container class Hbc::Container::Bzip2
==> Checking container class Hbc::Container::Gzip
==> Checking container class Hbc::Container::Lzma
==> Checking container class Hbc::Container::Xz
==> Checking container class Hbc::Container::Gpg
==> Checking container class Hbc::Container::Executable
==> Checking container class Hbc::Container::SvnRepository
==> Using container class Hbc::Container::SvnRepository for /Users/d1rk/Library/Caches/Homebrew/Cask/font-et-book--svn
==> Purging files for version latest of Cask font-et-book
Error: Is a directory - read
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1394:in `copy_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1394:in `block (2 levels) in copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1393:in `block in copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/directory.rb:13:in `block in extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/directory.rb:11:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/directory.rb:11:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:173:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```
#### Output of `brew cask doctor`

```
{{replace this}}
```

**Comment by commitay** [comment]
Please complete all of the steps in the template and provide all of the request information next time.

https://github.com/caskroom/homebrew-fonts/pull/1340

**Comment by d1rk** [comment]
@commitay I'm sorry, I omitted data for `brew cask doctor`. They are now provided with this. I checked all the points in the list, already, just thought it would be a reminder-list for myself. I was not aware to leave it in the issue and check those. The error remains the same.

**Comment by d1rk** [comment]
works now - thank you very much!
