### ISSUE TITLE
Download / install of Droid Font fails, looks the https://github.com/google/fonts/trunk/apache/droidsans is not longer available?

### ISSUE THREAD

**Issue by tobiashochguertel** [caskroom/homebrew-fonts#1366]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Can't install Droid font, It looks like that the git repository has changed from where homebrew tries to download the font?

```
1 hochguertelto@de-dus-nb-toh:~/03 Home/Users/hochguertelto/03 Home
$ brew cask install --force font-droid-sans font-droid-sans-ethiopic font-droid-sans-mono font-droid-sans-mono-for-powerline font-droid-sans-tamil font-droid-sans-thai font-droid-serif font-droid-serif-thai font-droidsansmono-nerd-font font-droidsansmono-nerd-font-mono font-droid-arabic-naskh font-droid-arabic-kufi
==> Satisfying dependencies
==> Checking out https://github.com/google/fonts/trunk/apache/droidsans
Error: Download failed on Cask 'font-droid-sans' with message: Command failed to execute!

==> Failed command:
/usr/bin/svn checkout --force --config-option config:miscellany:use-commit-times=yes --trust-server-cert --non-interactive https://github.com/google/fonts/trunk/apache/droidsans /Users/hochguertelto/Library/Caches/Homebrew/Cask/font-droid-sans--svn -r 50

==> Standard Output of failed command:


==> Standard Error of failed command:
svn: E160005: Target path '/trunk/apache/droidsans' does not exist


==> Exit status of failed command:
#<Process::Status: pid 28298 exit 1>
1 hochguertelto@de-dus-nb-toh:~/03 Home/Users/hochguertelto/03 Home
$
```

#### Output of your command with `--verbose --debug`

```
1 hochguertelto@de-dus-nb-toh:~/03 Home/Users/hochguertelto/03 Home
$ brew cask install --force --verbose --debug font-droid-sans font-droid-sans-ethiopic font-droid-sans-mono font-droid-sans-mono-for-powerline font-droid-sans-tamil font-droid-sans-thai font-droid-serif font-droid-serif-thai font-droidsansmono-nerd-font font-droidsansmono-nerd-font-mono font-droid-arabic-naskh font-droid-arabic-kufi
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Checking out https://github.com/google/fonts/trunk/apache/droidsans
==> Executing: ["/usr/bin/svn", "checkout", "--force", "--config-option", "config:miscellany:use-commit-times=yes", "--trust-server-cert", "--non-interactive", "https://github.com/google/fonts/trunk/apache/droidsans", "/Users/hochguertelto/Library/Caches/Homebrew/Cask/font-droid-sans--svn", "-r", "50"]
Error: Download failed on Cask 'font-droid-sans' with message: Command failed to execute!

==> Failed command:
/usr/bin/svn checkout --force --config-option config:miscellany:use-commit-times=yes --trust-server-cert --non-interactive https://github.com/google/fonts/trunk/apache/droidsans /Users/hochguertelto/Library/Caches/Homebrew/Cask/font-droid-sans--svn -r 50

==> Standard Output of failed command:


==> Standard Error of failed command:
svn: E160005: Target path '/trunk/apache/droidsans' does not exist


==> Exit status of failed command:
#<Process::Status: pid 28431 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:143:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:68:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:92:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
1 hochguertelto@de-dus-nb-toh:~/03 Home/Users/hochguertelto/03 Home
$
```

#### Output of `brew cask doctor`

```
1 hochguertelto@de-dus-nb-toh:~/03 Home/Users/hochguertelto/03 Home
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-217-g441c212
caskroom/homebrew-cask (git revision f73718; last commit 2017-11-12)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 1.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3814 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1121 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="de_DE.UTF-8"
PATH="/usr/local/opt/python/libexec/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/make/libexec/gnubin:~/.rvm/gems/ruby-2.4.1/bin:~/.rvm/gems/ruby-2.4.1@global/bin:~/.rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/glassfish/libexec/bin:~/.rvm/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
0 hochguertelto@de-dus-nb-toh:~/03 Home/Users/hochguertelto/03 Home
$
```

**Comment by commitay** [comment]
They have been removed by upstream.

https://github.com/google/fonts/issues/1223, https://github.com/google/fonts/pull/1275

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-fonts/pull/1367
